In [18]:
import numpy as np
import pandas as pd
import urllib.request

In [4]:
kento=np.array([73,67,43])

In [5]:
weight=np.array([0.2,0.3,0.5])

In [6]:
kento

array([73, 67, 43])

In [8]:
dot=np.dot(kento,weight)

In [9]:
dot

np.float64(56.2)

In [10]:
#multidimentional arrays

In [12]:
climate_data=np.array([[73,67,43],[91,88,64],[87,134,58],[102,43,37],[69,96,70]])

In [13]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [14]:
climate_data.shape

(5, 3)

In [15]:
weight

array([0.2, 0.3, 0.5])

In [16]:
climate_data.dtype

dtype('int64')

In [17]:
np.matmul(climate_data,weight)

array([56.2, 76.6, 86.6, 51.8, 77.6])

In [19]:
urllib.request.urlretrieve('https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x239a5e342c0>)

In [20]:
climate_db=np.genfromtxt('climate.txt',delimiter=',',skip_header=1)

In [21]:
climate_db

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]], shape=(10000, 3))

In [22]:
climate_db.shape

(10000, 3)

In [23]:
weight

array([0.2, 0.3, 0.5])

In [25]:
weight

array([0.2, 0.3, 0.5])

In [26]:
weight

array([0.2, 0.3, 0.5])

In [27]:
yields=climate_db @ weight

In [28]:
yields

array([77.3, 62.3, 63.8, ..., 67.4, 80.8, 68.1], shape=(10000,))

In [31]:
climate_result=np.concatenate((climate_db,yields.reshape(10000,1)),axis=1)

In [32]:
climate_result

array([[25. , 76. , 99. , 77.3],
       [39. , 65. , 70. , 62.3],
       [59. , 45. , 77. , 63.8],
       ...,
       [99. , 62. , 58. , 67.4],
       [70. , 71. , 91. , 80.8],
       [92. , 39. , 76. , 68.1]], shape=(10000, 4))

In [36]:
np.savetxt('climate_result.text',climate_result,fmt='%.2f',header='temp,rainfall,humidity,yield',comments='')

In [3]:
arr1=np.array([[23,45,67],[34,67,89],[23,56,43]]) 

NameError: name 'np' is not defined

In [4]:
kento

NameError: name 'kento' is not defined

In [5]:
weight

NameError: name 'weight' is not defined