In [1]:
import numpy as np

In [2]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
arr1+arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [5]:
arr1+3

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [6]:
arr2*5

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [8]:
(arr1+arr2).sum()

np.int64(90)

In [10]:
multi_arr=np.array([[[1,2,34],
                   [3,6,74]],
                  [[34,56,234],
                  [45,67,45]],
                  [[46,68,23],
                  [23,13,89]]]);

In [14]:
multi_arr

array([[[  1,   2,  34],
        [  3,   6,  74]],

       [[ 34,  56, 234],
        [ 45,  67,  45]],

       [[ 46,  68,  23],
        [ 23,  13,  89]]])

In [15]:
multi_arr

array([[[  1,   2,  34],
        [  3,   6,  74]],

       [[ 34,  56, 234],
        [ 45,  67,  45]],

       [[ 46,  68,  23],
        [ 23,  13,  89]]])

In [16]:
multi_arr.shape

(3, 2, 3)

In [18]:
multi_arr[1,0,2]

np.int64(234)

In [25]:
multi_arr[0:,0:1,:2]

array([[[ 1,  2]],

       [[34, 56]],

       [[46, 68]]])