In [1]:
import numpy as np

In [6]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [7]:
np.ones((2,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [9]:
np.full((2,2),99,dtype='int16')

array([[99, 99],
       [99, 99]], dtype=int16)

In [11]:
np.random.rand(2,3,4)

array([[[0.63750242, 0.77544417, 0.61596502, 0.76907859],
        [0.66879605, 0.1864654 , 0.44749273, 0.61902785],
        [0.96397929, 0.89502932, 0.55672066, 0.17339268]],

       [[0.10114068, 0.02213959, 0.61452374, 0.8190968 ],
        [0.21475775, 0.90375203, 0.00835418, 0.49591645],
        [0.42902676, 0.22111707, 0.97889352, 0.51346281]]])

In [14]:
np.random.randint(4,7,size=(3,3),dtype='int16')

array([[6, 6, 4],
       [5, 6, 5],
       [5, 6, 6]], dtype=int16)

In [16]:
np.identity(3,dtype='int32')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

In [46]:
arr=np.ones((5,5),dtype="int32")

In [47]:
arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [50]:
for i in range(1,4):
    for j in range(1,4):
        if arr[i,j]!=0:
            arr[i,j]=0

In [51]:
arr

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0]], dtype=int32)