In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5],dtype='int32')

In [4]:
print(a)

[1 2 3 4 5]


In [5]:
a

array([1, 2, 3, 4, 5], dtype=int32)

In [6]:
a+2

array([3, 4, 5, 6, 7], dtype=int32)

In [7]:
a**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [8]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [9]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [10]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [11]:
###linear Algebra

In [13]:
arr1=np.ones((2,3),dtype='int32')

In [15]:
arr2=np.full((3,2),99,dtype='int32')

In [16]:
arr1 @ arr2

array([[297, 297],
       [297, 297]], dtype=int32)

In [20]:
c=np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [21]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
before=np.array([[1,2,3],[5,6,7]]);

In [23]:
before

array([[1, 2, 3],
       [5, 6, 7]])

In [26]:
np.shape(before)

(2, 3)

In [35]:
after=before.reshape((3,2,1))

In [36]:
after

array([[[1],
        [2]],

       [[3],
        [5]],

       [[6],
        [7]]])

In [37]:
v1=np.ones((3,3))

In [38]:
v2=np.zeros((3,3))

In [40]:
np.vstack([v2,v1])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
np.hstack([v1,v1])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])