In [1]:
import numpy as np

In [30]:
climate_db=np.genfromtxt('climate.txt',delimiter=',',skip_header=1)
clic=climate_db.astype('int16')

In [17]:
climate_db.shape

(10000, 3)

In [35]:
np.all(climate_db>50,axis=0)

array([False, False, False])

In [31]:
clic.dtype

dtype('int16')

In [37]:
((climate_db>50)&(climate_db<100))

array([[False,  True,  True],
       [False,  True,  True],
       [ True, False,  True],
       ...,
       [ True,  True,  True],
       [ True,  True,  True],
       [ True, False,  True]], shape=(10000, 3))

In [38]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])

In [39]:
arr.shape

(6, 5)

In [40]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [41]:
arr[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [42]:
arr[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [ ]:
arr[[0,1,2,3]]